version: '3.8'

services:
  login:
    image: alpine
    secrets:
      - docker_username
      - docker_password
    entrypoint: sh -c 'echo "$$(cat /run/secrets/docker_password)" | docker login -u "$$(cat /run/secrets/docker_username)" --password-stdin && tail -f /dev/null'
    deploy:
      replicas: 1

  goapp:
    image: likith1710/inc42test
    ports:
      - "8080:8080"
    depends_on:
      - login
    secrets:
      - docker_username
      - docker_password
    deploy:
      replicas: 1

  nextjs:
    image: likith1710/nexjsapplication
    ports:
      - "3000:3000"
    depends_on:
      - login
    secrets:
      - docker_username
      - docker_password
    deploy:
      replicas: 1

  wordpress:
    image: likith1710/inc42test
    ports:
      - "80:80"
    depends_on:
      - login
    secrets:
      - docker_username
      - docker_password
    deploy:
      replicas: 1

secrets:
  docker_username:
    external: true
  docker_password:
    external: true

