version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root

  phpcs:
    build:
      context: .
      dockerfile: Dockerfile-phpcs
    volumes:
      - ./wordpress:/var/www/html
    command: >
      sh -c "phpcs --standard=WordPress /var/www/html"

volumes:
  db_data:

